#!/usr/bin/env php
<?php

define('APP_START_TIME', microtime(true));

require __DIR__ . '/vendor/autoload.php';

$console = Takemo101\Chubby\Console\Console::create(
    Takemo101\Chubby\ApplicationOption::from(
        basePath: $_ENV['APP_BASE_PATH'] ?? __DIR__,
    ),
);

// Functionality can be expanded by adding instances of classes that implement Provider.
// $console->addProvider(ExampleProvider::class);

$console->run();
