#!/usr/bin/env php
<?php

define('APP_START_TIME', microtime(true));

require __DIR__ . '/vendor/autoload.php';

$console = new Takemo101\Chubby\Console(
    Takemo101\Chubby\ApplicationBuilder::buildStandard(
        Takemo101\Chubby\ApplicationOption::from(
            basePath: getenv('APP_BASE_PATH') ?: __DIR__,
        ),
    ),
);

// Functionality can be expanded by adding instances of classes that implement Provider.
// $console->addProvider(ExampleProvider::class);

$console->run();
