version: '3'

# please install Taskfile => https://taskfile.dev/ja-JP/installation/

# template => https://go-task.github.io/slim-sprig/

vars:
  PINT_BIN: ./vendor/bin/pint
  PEST_BIN: ./vendor/bin/pest
  PHPSTAN_BIN: ./vendor/bin/phpstan

tasks:
  setup:
    cmds:
      - cp .example.env .env

  # ex: task composer -- install
  composer:
    cmds:
      - docker-compose run --rm composer {{default "--version" .CLI_ARGS}}

  change-ver:
    requires:
      vars: [ver, package]
    cmds:
      - docker-compose run --rm composer remove {{.package}}
      - docker-compose run --rm composer require {{.package}}:{{.ver}}

  start:
    cmds:
      - docker-compose up -d chubby-app

  shell:
    cmds:
      - docker-compose exec chubby-app bash

  stop:
    cmds:
      - docker-compose stop chubby-app

  pint:
    cmds:
      - docker-compose run --rm php {{.PINT_BIN}} --preset psr12 -v

  lint:
    cmds:
      - docker-compose run --rm php {{.PINT_BIN}} --test --preset psr12 -v

  analyze:
    cmds:
      - docker-compose run --rm php {{.PHPSTAN_BIN}} analyse --ansi --memory-limit=1G

  # ex: task test GROUP=xxx
  test:
    cmds:
      - docker-compose run --rm php {{.PEST_BIN}} --colors=always
        {{if .group}}--group={{.group}}{{end}}

  # ex: task serve PORT=8000 ROOT=./public/index.php
  serve:
    cmds:
      - php -S {{default "localhost" .host}}:{{default "8080" .port}} {{default "./public/index.php" .root}}
